// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get config from localStorage - no defaults for security
const getSupabaseConfig = () => {
  const stored = localStorage.getItem('supabase-config');
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      if (parsed.url && parsed.anonKey) {
        return parsed;
      }
    } catch {
      // Fall through to empty config
    }
  }
  return {
    url: '',
    anonKey: ''
  };
};

const config = getSupabaseConfig();
const SUPABASE_URL = config.url;
const SUPABASE_PUBLISHABLE_KEY = config.anonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});